---
title: "Some model output analysis rendered using RMarkdown"
author: "Marcus Low"
date: "April 2023"
output:
    html_document:  
        toc: false
        number_sections: false
        fig_height: 7
        fig_width: 7
theme: darkly
--- 

```{R load_the_basics, include=FALSE}
a4 <- read.csv("a4.csv")
a8 <- read.csv("a8.csv")
a12 <- read.csv("a12.csv")
a16 <- read.csv("a16.csv")
a20 <- read.csv("a20.csv")
a24 <- read.csv("a24.csv")
a28 <- read.csv("a28.csv")
a32 <- read.csv("a32.csv")
a36 <- read.csv("a36.csv")
a40 <- read.csv("a40.csv")
a44 <- read.csv("a44.csv")
a48 <- read.csv("a48.csv")
a52 <- read.csv("a52.csv")
a4s8 <- read.csv("a4s8.csv")
a8s8 <- read.csv("a8s8.csv")
a12s8 <- read.csv("a12s8.csv")
a16s8 <- read.csv("a16s8.csv")
a20s8 <- read.csv("a20s8.csv")
a24s8 <- read.csv("a24s8.csv")
a28s8 <- read.csv("a28s8.csv")
a32s8 <- read.csv("a32s8.csv")
a36s8 <- read.csv("a36s8.csv")
a40s8 <- read.csv("a40s8.csv")
a44s8 <- read.csv("a44s8.csv")
a48s8 <- read.csv("a48s8.csv")
a52s8 <- read.csv("a52s8.csv")

a4s9 <- read.csv("a4s9.csv")
a8s9 <- read.csv("a8s9.csv")
a12s9 <- read.csv("a12s9.csv")
a16s9 <- read.csv("a16s9.csv")
a20s9 <- read.csv("a20s9.csv")
a24s9 <- read.csv("a24s9.csv")
a28s9 <- read.csv("a28s9.csv")
a32s9 <- read.csv("a32s9.csv")
a36s9 <- read.csv("a36s9.csv")
a40s9 <- read.csv("a40s9.csv")
a44s9 <- read.csv("a44s9.csv")
a48s9 <- read.csv("a48s9.csv")
a52s9 <- read.csv("a52s9.csv")
a4s1 <- read.csv("a4s1.csv")
a8s1 <- read.csv("a8s1.csv")
a12s1 <- read.csv("a12s1.csv")
a16s1 <- read.csv("a16s1.csv")
a20s1 <- read.csv("a20s1.csv")
a24s1 <- read.csv("a24s1.csv")
a28s1 <- read.csv("a28s1.csv")
a32s1 <- read.csv("a32s1.csv")
a36s1 <- read.csv("a36s1.csv")
a40s1 <- read.csv("a40s1.csv")
a44s1 <- read.csv("a44s1.csv")
a48s1 <- read.csv("a48s1.csv")
a52s1 <- read.csv("a52s1.csv")
library(dplyr)
library(ggplot2)
library(gridExtra)
library(htmlTable)
runs_count <- length(a4$latent_infections)
```

# Analysis {.tabset .tabset-fade .tabset-pills}

## The numbers
The below is based on `r runs_count` runs of the model.

Some basics

```{R basic_numbers, echo = FALSE}
a4 <- dplyr::filter(a4, Time_step == 519)
a8 <- dplyr::filter(a8, Time_step == 519)
a12 <- dplyr::filter(a12, Time_step == 519)
a16 <- dplyr::filter(a16, Time_step == 519)
a20 <- dplyr::filter(a20, Time_step == 519)
a24 <- dplyr::filter(a24, Time_step == 519)
a28 <- dplyr::filter(a28, Time_step == 519)
a32 <- dplyr::filter(a32, Time_step == 519)
a36 <- dplyr::filter(a36, Time_step == 519)
a40 <- dplyr::filter(a40, Time_step == 519)
a44 <- dplyr::filter(a44, Time_step == 519)
a48 <- dplyr::filter(a48, Time_step == 519)
a52 <- dplyr::filter(a52, Time_step == 519)
a4s8 <- dplyr::filter(a4s8, Time_step == 519)
a8s8 <- dplyr::filter(a8s8, Time_step == 519)
a12s8 <- dplyr::filter(a12s8, Time_step == 519)
a16s8 <- dplyr::filter(a16s8, Time_step == 519)
a20s8 <- dplyr::filter(a20s8, Time_step == 519)
a24s8 <- dplyr::filter(a24s8, Time_step == 519)
a28s8 <- dplyr::filter(a28s8, Time_step == 519)
a32s8 <- dplyr::filter(a32s8, Time_step == 519)
a36s8 <- dplyr::filter(a36s8, Time_step == 519)
a40s8 <- dplyr::filter(a40s8, Time_step == 519)
a44s8 <- dplyr::filter(a44s8, Time_step == 519)
a48s8 <- dplyr::filter(a48s8, Time_step == 519)
a52s8 <- dplyr::filter(a52s8, Time_step == 519)
a4s9 <- dplyr::filter(a4s9, Time_step == 519)
a8s9 <- dplyr::filter(a8s9, Time_step == 519)
a12s9 <- dplyr::filter(a12s9, Time_step == 519)
a16s9 <- dplyr::filter(a16s9, Time_step == 519)
a20s9 <- dplyr::filter(a20s9, Time_step == 519)
a24s9 <- dplyr::filter(a24s9, Time_step == 519)
a28s9 <- dplyr::filter(a28s9, Time_step == 519)
a32s9 <- dplyr::filter(a32s9, Time_step == 519)
a36s9 <- dplyr::filter(a36s9, Time_step == 519)
a40s9 <- dplyr::filter(a40s9, Time_step == 519)
a44s9 <- dplyr::filter(a44s9, Time_step == 519)
a48s9 <- dplyr::filter(a48s9, Time_step == 519)
a52s9 <- dplyr::filter(a52s9, Time_step == 519)
a4s1 <- dplyr::filter(a4s1, Time_step == 519)
a8s1 <- dplyr::filter(a8s1, Time_step == 519)
a12s1 <- dplyr::filter(a12s1, Time_step == 519)
a16s1 <- dplyr::filter(a16s1, Time_step == 519)
a20s1 <- dplyr::filter(a20s1, Time_step == 519)
a24s1 <- dplyr::filter(a24s1, Time_step == 519)
a28s1 <- dplyr::filter(a28s1, Time_step == 519)
a32s1 <- dplyr::filter(a32s1, Time_step == 519)
a36s1 <- dplyr::filter(a36s1, Time_step == 519)
a40s1 <- dplyr::filter(a40s1, Time_step == 519)
a44s1 <- dplyr::filter(a44s1, Time_step == 519)
a48s1 <- dplyr::filter(a48s1, Time_step == 519)
a52s1 <- dplyr::filter(a52s1, Time_step == 519)

a <- data.frame("Weeks" = c(4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52),
"Dead7" = c(mean(a4$Dead), mean(a8$Dead),mean(a12$Dead),mean(a16$Dead),mean(a20$Dead),mean(a24$Dead),mean(a28$Dead),mean(a32$Dead),mean(a36$Dead),mean(a40$Dead),mean(a44$Dead),mean(a48$Dead),mean(a52$Dead)),
"Dead8" = c(mean(a4s8$Dead), mean(a8s8$Dead),mean(a12s8$Dead),mean(a16s8$Dead),mean(a20s8$Dead),mean(a24s8$Dead),mean(a28s8$Dead),mean(a32s8$Dead),mean(a36s8$Dead),mean(a40s8$Dead),mean(a44s8$Dead),mean(a48s8$Dead),mean(a52s8$Dead)),
"Dead9" = c(mean(a4s9$Dead), mean(a8s9$Dead),mean(a12s9$Dead),mean(a16s9$Dead),mean(a20s9$Dead),mean(a24s9$Dead),mean(a28s9$Dead),mean(a32s9$Dead),mean(a36s9$Dead),mean(a40s9$Dead),mean(a44s9$Dead),mean(a48s9$Dead),mean(a52s9$Dead)),
"Dead10" = c(mean(a4s1$Dead), mean(a8s1$Dead),mean(a12s1$Dead),mean(a16s1$Dead),mean(a20s1$Dead),mean(a24s1$Dead),mean(a28s1$Dead),mean(a32s1$Dead),mean(a36s1$Dead),mean(a40s1$Dead),mean(a44s1$Dead),mean(a48s1$Dead),mean(a52s1$Dead)),
"Active7" =c(mean(a4$agents_ever_active), mean(a8$agents_ever_active),mean(a12$agents_ever_active),mean(a16$agents_ever_active),mean(a20$agents_ever_active),mean(a24$agents_ever_active),mean(a28$agents_ever_active),mean(a32$agents_ever_active),mean(a36$agents_ever_active),mean(a40$agents_ever_active),mean(a44$agents_ever_active),mean(a48$agents_ever_active),mean(a52$agents_ever_active)),
"Active8" =c(mean(a4s8$agents_ever_active), mean(a8s8$agents_ever_active),mean(a12s8$agents_ever_active),mean(a16s8$agents_ever_active),mean(a20s8$agents_ever_active),mean(a24s8$agents_ever_active),mean(a28s8$agents_ever_active),mean(a32s8$agents_ever_active),mean(a36s8$agents_ever_active),mean(a40s8$agents_ever_active),mean(a44s8$agents_ever_active),mean(a48s8$agents_ever_active),mean(a52s8$agents_ever_active)),
"Active9" =c(mean(a4s9$agents_ever_active), mean(a8s9$agents_ever_active),mean(a12s9$agents_ever_active),mean(a16s9$agents_ever_active),mean(a20s9$agents_ever_active),mean(a24s9$agents_ever_active),mean(a28s9$agents_ever_active),mean(a32s9$agents_ever_active),mean(a36s9$agents_ever_active),mean(a40s9$agents_ever_active),mean(a44s9$agents_ever_active),mean(a48s9$agents_ever_active),mean(a52s9$agents_ever_active)),
"Active10" =c(mean(a4s1$agents_ever_active), mean(a8s1$agents_ever_active),mean(a12s1$agents_ever_active),mean(a16s1$agents_ever_active),mean(a20s1$agents_ever_active),mean(a24s1$agents_ever_active),mean(a28s1$agents_ever_active),mean(a32s1$agents_ever_active),mean(a36s1$agents_ever_active),mean(a40s1$agents_ever_active),mean(a44s1$agents_ever_active),mean(a48s1$agents_ever_active),mean(a52s1$agents_ever_active)),
"TimeInfectious7" = c(mean(a4$mean_time_infectious), mean(a8$mean_time_infectious),mean(a12$mean_time_infectious),mean(a16$mean_time_infectious),mean(a20$mean_time_infectious),mean(a24$mean_time_infectious),mean(a28$mean_time_infectious),mean(a32$mean_time_infectious),mean(a36$mean_time_infectious),mean(a40$mean_time_infectious),mean(a44$mean_time_infectious),mean(a48$mean_time_infectious),mean(a52$mean_time_infectious)),
"TimeInfectious8" = c(mean(a4s8$mean_time_infectious), mean(a8s8$mean_time_infectious),mean(a12s8$mean_time_infectious),mean(a16s8$mean_time_infectious),mean(a20s8$mean_time_infectious),mean(a24s8$mean_time_infectious),mean(a28s8$mean_time_infectious),mean(a32s8$mean_time_infectious),mean(a36s8$mean_time_infectious),mean(a40s8$mean_time_infectious),mean(a44s8$mean_time_infectious),mean(a48s8$mean_time_infectious),mean(a52s8$mean_time_infectious)),
"TimeInfectious9" = c(mean(a4s9$mean_time_infectious), mean(a8s9$mean_time_infectious),mean(a12s9$mean_time_infectious),mean(a16s9$mean_time_infectious),mean(a20s9$mean_time_infectious),mean(a24s9$mean_time_infectious),mean(a28s9$mean_time_infectious),mean(a32s9$mean_time_infectious),mean(a36s9$mean_time_infectious),mean(a40s9$mean_time_infectious),mean(a44s9$mean_time_infectious),mean(a48s9$mean_time_infectious),mean(a52s9$mean_time_infectious)),
"TimeInfectious10" = c(mean(a4s1$mean_time_infectious), mean(a8s1$mean_time_infectious),mean(a12s1$mean_time_infectious),mean(a16s1$mean_time_infectious),mean(a20s1$mean_time_infectious),mean(a24s1$mean_time_infectious),mean(a28s1$mean_time_infectious),mean(a32s1$mean_time_infectious),mean(a36s1$mean_time_infectious),mean(a40s1$mean_time_infectious),mean(a44s1$mean_time_infectious),mean(a48s1$mean_time_infectious),mean(a52s1$mean_time_infectious)),
"TimeActive7" = c(mean(a4$mean_time_active), mean(a8$mean_time_active),mean(a12$mean_time_active),mean(a16$mean_time_active),mean(a20$mean_time_active),mean(a24$mean_time_active),mean(a28$mean_time_active),mean(a32$mean_time_active),mean(a36$mean_time_active),mean(a40$mean_time_active),mean(a44$mean_time_active),mean(a48$mean_time_active),mean(a52$mean_time_active)),
"TimeActive8" = c(mean(a4s8$mean_time_active), mean(a8s8$mean_time_active),mean(a12s8$mean_time_active),mean(a16s8$mean_time_active),mean(a20s8$mean_time_active),mean(a24s8$mean_time_active),mean(a28s8$mean_time_active),mean(a32s8$mean_time_active),mean(a36s8$mean_time_active),mean(a40s8$mean_time_active),mean(a44s8$mean_time_active),mean(a48s8$mean_time_active),mean(a52s8$mean_time_active)),
"TimeActive9" = c(mean(a4s9$mean_time_active), mean(a8s9$mean_time_active),mean(a12s9$mean_time_active),mean(a16s9$mean_time_active),mean(a20s9$mean_time_active),mean(a24s9$mean_time_active),mean(a28s9$mean_time_active),mean(a32s9$mean_time_active),mean(a36s9$mean_time_active),mean(a40s9$mean_time_active),mean(a44s9$mean_time_active),mean(a48s9$mean_time_active),mean(a52s9$mean_time_active)),
"TimeActive10" = c(mean(a4s1$mean_time_active), mean(a8s1$mean_time_active),mean(a12s1$mean_time_active),mean(a16s1$mean_time_active),mean(a20s1$mean_time_active),mean(a24s1$mean_time_active),mean(a28s1$mean_time_active),mean(a32s1$mean_time_active),mean(a36s1$mean_time_active),mean(a40s1$mean_time_active),mean(a44s1$mean_time_active),mean(a48s1$mean_time_active),mean(a52s1$mean_time_active))
)
htmlTable(a)
```

Some key uncertainty ranges

```{R uncertainty, echo = FALSE}
a4activeL <- quantile(a4$agents_ever_active, probs =0.025)
a4activeH <- quantile(a4$agents_ever_active, probs =0.975)
a4deadL <- quantile(a4$Dead, probs =0.025)
a4deadH <- quantile(a4$Dead, probs =0.975)
a4timeinfectL <- quantile(a4$mean_time_infectious, probs =0.025)
a4timeinfectH <- quantile(a4$mean_time_infectious, probs =0.975)
a4timeactiveL <- quantile(a4$mean_time_active, probs =0.025)
a4timeactiveH <- quantile(a4$mean_time_active, probs =0.975)

a4s1activeL <- quantile(a4s1$agents_ever_active, probs =0.025)
a4s1activeH <- quantile(a4s1$agents_ever_active, probs =0.975)
a4s1deadL <- quantile(a4s1$Dead, probs =0.025)
a4s1deadH <- quantile(a4s1$Dead, probs =0.975)
a4s1timeinfectL <- quantile(a4s1$mean_time_infectious, probs =0.025)
a4s1timeinfectH <- quantile(a4s1$mean_time_infectious, probs =0.975)
a4s1timeactiveL <- quantile(a4s1$mean_time_active, probs =0.025)
a4s1timeactiveH <- quantile(a4s1$mean_time_active, probs =0.975)

a52activeL <- quantile(a52$agents_ever_active, probs =0.025)
a52activeH <- quantile(a52$agents_ever_active, probs =0.975)
a52deadL <- quantile(a52$Dead, probs =0.025)
a52deadH <- quantile(a52$Dead, probs =0.975)
a52timeinfectL <- quantile(a52$mean_time_infectious, probs =0.025)
a52timeinfectH <- quantile(a52$mean_time_infectious, probs =0.975)
a52timeactiveL <- quantile(a52$mean_time_active, probs =0.025)
a52timeactiveH <- quantile(a52$mean_time_active, probs =0.975)

a52s1activeL <- quantile(a52s1$agents_ever_active, probs =0.025)
a52s1activeH <- quantile(a52s1$agents_ever_active, probs =0.975)
a52s1deadL <- quantile(a52s1$Dead, probs =0.025)
a52s1deadH <- quantile(a52s1$Dead, probs =0.975)
a52s1timeinfectL <- quantile(a52s1$mean_time_infectious, probs =0.025)
a52s1timeinfectH <- quantile(a52s1$mean_time_infectious, probs =0.975)
a52s1timeactiveL <- quantile(a52s1$mean_time_active, probs =0.025)
a52s1timeactiveH <- quantile(a52s1$mean_time_active, probs =0.975)

a4s8activeL <- quantile(a4s8$agents_ever_active, probs =0.025)
a4s8activeH <- quantile(a4s8$agents_ever_active, probs =0.975)
a4s8deadL <- quantile(a4s8$Dead, probs =0.025)
a4s8deadH <- quantile(a4s8$Dead, probs =0.975)
a4s8timeinfectL <- quantile(a4s8$mean_time_infectious, probs =0.025)
a4s8timeinfectH <- quantile(a4s8$mean_time_infectious, probs =0.975)
a4s8timeactiveL <- quantile(a4s8$mean_time_active, probs =0.025)
a4s8timeactiveH <- quantile(a4s8$mean_time_active, probs =0.975)

a4s9activeL <- quantile(a4s9$agents_ever_active, probs =0.025)
a4s9activeH <- quantile(a4s9$agents_ever_active, probs =0.975)
a4s9deadL <- quantile(a4s9$Dead, probs =0.025)
a4s9deadH <- quantile(a4s9$Dead, probs =0.975)
a4s9timeinfectL <- quantile(a4s9$mean_time_infectious, probs =0.025)
a4s9timeinfectH <- quantile(a4s9$mean_time_infectious, probs =0.975)
a4s9timeactiveL <- quantile(a4s9$mean_time_active, probs =0.025)
a4s9timeactiveH <- quantile(a4s9$mean_time_active, probs =0.975)

a52s8activeL <- quantile(a52s8$agents_ever_active, probs =0.025)
a52s8activeH <- quantile(a52s8$agents_ever_active, probs =0.975)
a52s8deadL <- quantile(a52s8$Dead, probs =0.025)
a52s8deadH <- quantile(a52s8$Dead, probs =0.975)
a52s8timeinfectL <- quantile(a52s8$mean_time_infectious, probs =0.025)
a52s8timeinfectH <- quantile(a52s8$mean_time_infectious, probs =0.975)
a52s8timeactiveL <- quantile(a52s8$mean_time_active, probs =0.025)
a52s8timeactiveH <- quantile(a52s8$mean_time_active, probs =0.975)

a52s9activeL <- quantile(a52s9$agents_ever_active, probs =0.025)
a52s9activeH <- quantile(a52s9$agents_ever_active, probs =0.975)
a52s9deadL <- quantile(a52s9$Dead, probs =0.025)
a52s9deadH <- quantile(a52s9$Dead, probs =0.975)
a52s9timeinfectL <- quantile(a52s9$mean_time_infectious, probs =0.025)
a52s9timeinfectH <- quantile(a52s9$mean_time_infectious, probs =0.975)
a52s9timeactiveL <- quantile(a52s9$mean_time_active, probs =0.025)
a52s9timeactiveH <- quantile(a52s9$mean_time_active, probs =0.975)
```

4-weekly with 70% sensitivity

Cases: `r a4activeL` `r a4activeH`

Deaths: `r a4deadL` `r a4deadH`

Time infectious: `r a4timeinfectL` `r a4timeinfectH` 

Time active: `r a4timeactiveL` `r a4timeactiveH`

4-weekly with 80% sensitivity

Cases: `r a4s8activeL` `r a4s8activeH`

Deaths: `r a4s8deadL` `r a4s8deadH`

Time infectious: `r a4s8timeinfectL` `r a4s8timeinfectH` 

Time active: `r a4s8timeactiveL` `r a4s8timeactiveH`

4-weekly with 90% sensitivity

Cases: `r a4s9activeL` `r a4s9activeH`

Deaths: `r a4s9deadL` `r a4s9deadH`

Time infectious: `r a4s9timeinfectL` `r a4s9timeinfectH` 

Time active: `r a4s9timeactiveL` `r a4s9timeactiveH`

4-weekly with 100% sensitivity

Cases: `r a4s1activeL` `r a4s1activeH`

Deaths: `r a4s1deadL` `r a4s1deadH`

Time infectious: `r a4s1timeinfectL` `r a4s1timeinfectH` 

Time active: `r a4s1timeactiveL` `r a4s1timeactiveH`

52-weekly with 70% sensitivity

Cases: `r a52activeL` `r a52activeH`

Deaths: `r a52deadL` `r a52deadH`

Time infectious: `r a52timeinfectL` `r a52timeinfectH` 

Time active: `r a52timeactiveL` `r a52timeactiveH`

52-weekly with 80% sensitivity

Cases: `r a52s8activeL` `r a52s8activeH`

Deaths: `r a52s8deadL` `r a52s8deadH`

Time infectious: `r a52s8timeinfectL` `r a52s8timeinfectH` 

Time active: `r a52s8timeactiveL` `r a52s8timeactiveH`

52-weekly with 90% sensitivity

Cases: `r a52s9activeL` `r a52s9activeH`

Deaths: `r a52s9deadL` `r a52s9deadH`

Time infectious: `r a52s9timeinfectL` `r a52s9timeinfectH` 

Time active: `r a52s9timeactiveL` `r a52s9timeactiveH`

52-weekly with 100% sensitivity

Cases: `r a52s1activeL` `r a52s1activeH`

Deaths: `r a52s1deadL` `r a52s1deadH`

Time infectious: `r a52s1timeinfectL` `r a52s1timeinfectH` 

Time active: `r a52s1timeactiveL` `r a52s1timeactiveH`


And some graphs. First infections 

```{R Infections_curves, echo = FALSE}
library(reshape2)
a_graph <- select(a, Weeks, Active7, Active8, Active9, Active10)
colnames(a_graph) <- c("Weeks", "70% sensitivity", "80% sensitivity", "90% sensitivity", "100% sensitivity")
a_graph <- reshape2::melt(a_graph, id.vars = "Weeks")
ggplot(data = a_graph, aes(x = Weeks, y = value, colour = variable)) +
geom_line() +
  labs(x = "Weeks", y = "Mean active TB cases", title ="Test frequency and mean cases of active TB") +
  theme_gray()
ggsave("fig5.png")
```

and deaths

```{R deaths_curves, echo = FALSE}
a_graph <- select(a, Weeks, Dead7, Dead8, Dead9, Dead10)
colnames(a_graph) <- c("Weeks", "70% sensitivity", "80% sensitivity", "90% sensitivity", "100% sensitivity")
a_graph <- reshape2::melt(a_graph, id.vars = "Weeks")
ggplot(data = a_graph, aes(x = Weeks, y = value, colour = variable)) +
geom_line() +
  labs(x = "Weeks", y = "Mean TB deaths", title ="Test frequency and mean TB deaths") +
   theme_gray()  
ggsave("fig6.png")
```

And time infectious 

```{R time_infectious_curves, echo = FALSE}
a_graph <- select(a, Weeks, TimeInfectious7, TimeInfectious8, TimeInfectious9, TimeInfectious10)
colnames(a_graph) <- c("Weeks", "70% sensitivity", "80% sensitivity", "90% sensitivity", "100% sensitivity")
a_graph <- reshape2::melt(a_graph, id.vars = "Weeks")
ggplot(data = a_graph, aes(x = Weeks, y = value, colour = variable)) +
geom_line() +
  labs(x = "Weeks", y = "Mean period infectious", title ="Test frequency and mean infectious period") +
  theme_gray()  
ggsave("fig7.png")
```

And time active

```{R time_active_curves, echo = FALSE}
a_graph <- select(a, Weeks, TimeActive7, TimeActive8, TimeActive9, TimeActive10)
colnames(a_graph) <- c("Weeks", "70% sensitivity", "80% sensitivity", "90% sensitivity", "100% sensitivity")
a_graph <- reshape2::melt(a_graph, id.vars = "Weeks")
ggplot(data = a_graph, aes(x = Weeks, y = value, colour = variable)) +
geom_line() +
  labs(x = "Weeks", y = "Mean period active TB", title ="Test frequency and mean period with active disease") +
  theme_gray()
ggsave("fig8.png")
```




